import { createClient } from "@/lib/supabase/server";
import { updatePartner } from "./actions";
import { ExternalLink, Users } from "lucide-react";

export const dynamic = "force-dynamic";
const labels: Record<string, string> = { guide: "ไกด์", hotel: "โรงแรม", driver: "คนขับรถ", agent: "เอเจนต์", pending: "รอตรวจสอบ", approved: "อนุมัติแล้ว", suspended: "ระงับ", rejected: "ไม่อนุมัติ" };
const statusStyle: Record<string, string> = { pending: "bg-amber-100 text-amber-800", approved: "bg-emerald-100 text-emerald-800", suspended: "bg-red-100 text-red-700", rejected: "bg-slate-100 text-slate-600" };

export default async function PartnersAdminPage() {
  const { data: partners } = await createClient().from("partners").select("*").order("created_at", { ascending: false });
  const pending = (partners ?? []).filter((p) => p.status === "pending").length;
  return <div><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-brand-teal">AFFILIATE MANAGEMENT</p><h1 className="text-2xl font-bold text-brand-text">จัดการพาร์ทเนอร์ / ไกด์</h1></div><div className="rounded-xl bg-amber-50 px-4 py-2 text-sm text-amber-800">รอตรวจสอบ {pending} รายการ</div></div>
    <div className="overflow-hidden rounded-2xl bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[960px] text-sm"><thead className="bg-slate-50 text-left text-brand-text/60"><tr><th className="px-4 py-3">พาร์ทเนอร์</th><th className="px-4 py-3">ประเภท</th><th className="px-4 py-3">ติดต่อ / ธนาคาร</th><th className="px-4 py-3">Affiliate Code</th><th className="px-4 py-3">คอมมิชชัน</th><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3"></th></tr></thead><tbody>{(partners ?? []).map((p) => <tr key={p.id} className="border-t border-black/5 align-top"><td className="px-4 py-4 font-medium"><div>{p.full_name}</div><div className="mt-1 text-xs font-normal text-brand-text/50">สมัคร {new Date(p.created_at).toLocaleDateString("th-TH")}</div></td><td className="px-4 py-4"><span className="rounded-md bg-teal-50 px-2 py-1 text-xs text-teal-800">{labels[p.partner_type]}</span></td><td className="px-4 py-4 text-xs leading-5 text-brand-text/70"><div>{p.phone} {p.line_id && `· LINE ${p.line_id}`}</div><div>{p.bank_name} · {p.bank_account_number}</div><div>{p.bank_account_name}</div></td><td className="px-4 py-4">{p.affiliate_code ? <a href={`/ref/${p.affiliate_code}`} target="_blank" className="inline-flex items-center gap-1 font-semibold text-brand-teal hover:underline">{p.affiliate_code}<ExternalLink size={13}/></a> : <span className="text-brand-text/35">จะสร้างเมื่ออนุมัติ</span>}</td><td className="px-4 py-4">{p.commission_rate}%</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusStyle[p.status]}`}>{labels[p.status]}</span></td><td className="px-4 py-4"><form action={updatePartner} className="flex items-center gap-2"><input type="hidden" name="id" value={p.id}/><input className="w-14 rounded-lg border border-black/10 px-2 py-1.5 text-xs" type="number" name="commission_rate" min="0" max="100" step="0.5" defaultValue={p.commission_rate}/><select name="status" defaultValue={p.status} className="rounded-lg border border-black/10 px-2 py-1.5 text-xs"><option value="pending">รอตรวจสอบ</option><option value="approved">อนุมัติ</option><option value="suspended">ระงับ</option><option value="rejected">ไม่อนุมัติ</option></select><button className="rounded-lg bg-brand-green px-3 py-1.5 text-xs font-medium text-white">บันทึก</button></form></td></tr>)}{!partners?.length && <tr><td colSpan={7} className="px-4 py-14 text-center text-brand-text/50"><Users className="mx-auto mb-2"/>ยังไม่มีใบสมัครพาร์ทเนอร์</td></tr>}</tbody></table></div></div></div>;
}
