import { createAdminClient } from "@/lib/supabase/server";
import { formatTHB } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function RevenuePage() {
  const db = createAdminClient();
  const { data: rows } = await db.from("booking_revenue_splits").select("*, bookings(booking_number, booking_status, tours(title_th), packages(name_th))").order("created_at", { ascending: false });
  const totals = (rows ?? []).filter((row: any) => row.status !== "void").reduce((sum: any, row: any) => ({ gross: sum.gross + row.gross_amount, partner: sum.partner + row.partner_amount, platform: sum.platform + row.platform_amount, operator: sum.operator + row.operator_amount }), { gross: 0, partner: 0, platform: 0, operator: 0 });
  return <div><h1 className="text-2xl font-bold text-brand-text">สรุปแบ่งรายได้กิจกรรม</h1><p className="mt-1 text-sm text-brand-text/55">ข้อมูลจะสร้างอัตโนมัติหลัง Stripe ชำระเงินสำเร็จ</p><div className="mt-6 grid gap-3 sm:grid-cols-4">{[["ลูกค้าชำระ",totals.gross],["พาร์ทเนอร์",totals.partner],["ค่าระบบ",totals.platform],["ผู้ประกอบการ",totals.operator]].map(([label,value]) => <div key={String(label)} className="rounded-2xl bg-white p-5 shadow-soft"><div className="text-sm text-brand-text/55">{label}</div><div className="mt-2 text-xl font-bold text-brand-text">{formatTHB(Number(value))}</div></div>)}</div><div className="mt-6 overflow-hidden rounded-2xl bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-brand-bg text-left text-brand-text/55"><tr><th className="px-4 py-3">รายการ</th><th className="px-4 py-3">ลูกค้าจ่าย</th><th className="px-4 py-3">พาร์ทเนอร์</th><th className="px-4 py-3">ค่าระบบ</th><th className="px-4 py-3">ผู้ประกอบการ</th><th className="px-4 py-3">สถานะ</th></tr></thead><tbody>{(rows ?? []).map((row: any) => <tr key={row.id} className="border-t border-black/5"><td className="px-4 py-3"><b>{row.bookings?.booking_number}</b><div className="text-xs text-brand-text/55">{row.bookings?.tours?.title_th} · {row.bookings?.packages?.name_th}</div></td><td className="px-4 py-3">{formatTHB(row.gross_amount)}</td><td className="px-4 py-3 text-brand-orange">{formatTHB(row.partner_amount)}</td><td className="px-4 py-3 text-brand-teal">{formatTHB(row.platform_amount)}</td><td className="px-4 py-3 font-semibold">{formatTHB(row.operator_amount)}</td><td className="px-4 py-3">{row.status === "void" ? "ยกเลิก" : row.status === "available" ? "พร้อมจ่าย" : "รอใช้บริการ"}</td></tr>)}{!rows?.length && <tr><td colSpan={6} className="px-4 py-10 text-center text-brand-text/55">ยังไม่มีรายการแบ่งรายได้</td></tr>}</tbody></table></div></div></div>;
}
